language: node_js
dist: trusty
sudo: required
node_js: 10
install:
  - npm install -g bower
  - npm install
  - bower install --production
script:
  - npm run -s build
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
